# Generated by Django 2.2.4 on 2019-10-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20191003_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='stars',
            field=models.ManyToManyField(related_name='starred_by', to='main.Entry'),
        ),
    ]
