# Generated by Django 2.2.4 on 2019-10-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20191022_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='comments',
            field=models.ManyToManyField(null=True, related_name='comment_by', to='main.Comment'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='stars',
            field=models.ManyToManyField(null=True, related_name='starred_by', to='main.Entry'),
        ),
    ]
