# Generated by Django 2.2.4 on 2019-10-22 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20191022_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='stars',
        ),
    ]
